# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-04-03 01:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_filename', models.CharField(default='', max_length=30)),
                ('breed', models.CharField(default='unknown breed', max_length=255)),
                ('age', models.IntegerField(blank=True, default=1)),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female'), ('u', 'unknown')], default='unknown', max_length=15)),
                ('size', models.CharField(choices=[('s', 'small'), ('m', 'medium'), ('l', 'large'), ('xl', 'extra large'), ('u', 'unknown')], default='unknown', max_length=10)),
                ('sterilized', models.CharField(choices=[('y', 'yes'), ('n', 'no')], default='unknwon', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserDog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('l', 'liked'), ('d', 'disliked')], default='undecided', max_length=10)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pugorugh.Dog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(choices=[('b', 'baby'), ('y', 'young'), ('a', 'adult'), ('s', 'senior')], default='b,y,a,s', max_length=10)),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female'), ('u', 'unknown')], default='f,m', max_length=15)),
                ('size', models.CharField(choices=[('s', 'small'), ('m', 'medium'), ('l', 'large'), ('xl', 'extra large'), ('u', 'unknown')], default='s,m,l,xl', max_length=10)),
                ('sterilized', models.CharField(choices=[('y', 'yes'), ('n', 'no')], default='y,n', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
